Repository Cogoport/eslint-config, pull requests merged in 2023-06, with the labels that each got.

#4 Demo custom lints
  custom-rules.js
  package.json
  packages/eslint/index.js
  packages/eslint/package.json
Labels: 5 min review

#8 is-empty-use-check
  custom-rules.js
  custom_rules/is-empty-use-check/index.js
  packages/eslint/index.js
  packages/eslint/is_empty_use_check.js
  react-typescript.js
Labels: 10 min review

#7 nbsp-check
  custom-rules.js
  custom_rules/is-empty-use-check/index.js
  custom_rules/regex-check/index.js
  packages/eslint/index.js
  packages/eslint/is_empty_use_check.js
  packages/eslint/nbsp_ensp_check.js
  packages/eslint/regex_check.js
  react-typescript.js
Labels: 1 min review

#6 Regex check
  custom-rules.js
  custom_rules/is-empty-use-check/index.js
  packages/eslint/img_src_cdn.js
  packages/eslint/index.js
  packages/eslint/is_empty_use_check.js
  packages/eslint/nbsp_ensp_check.js
  packages/eslint/regex_check.js
  react-typescript.js
Labels: 10 min review

#9 UUID and email
  custom-rules.js
  packages/eslint/email_check.js
  packages/eslint/index.js
  packages/eslint/uuid_check.js
  pnpm-lock.yaml
Labels: 5 min review

#11 date time format check
  custom-rules.js
  packages/eslint/date_time_format_check.js
  packages/eslint/index.js
Labels: 1 min review

#13 Zeroth-index-import
  custom-rules.js
  packages/eslint/index.js
  packages/eslint/zeroth_index_import.js
Labels: 1 min review

#14 key checks
  custom-rules.js
  packages/eslint/index.js
  packages/eslint/key_as_function.js
  packages/eslint/key_in_for_each.js
Labels: 5 min review

#20 fix: rule
  custom-rules.js
  packages/eslint/component_pascal.js
  packages/eslint/index.js
Labels: 1 min review

#22 hook sequence
  custom-rules.js
  packages/eslint/hook_sequence.js
  packages/eslint/index.js
Labels: 1 min review

#24 fix: usestate
  custom-rules.js
  packages/eslint/default_usestate.js
  packages/eslint/index.js
Labels: 1 min review

#21 snake_case & camelCase variable
  custom-rules.js
  packages/eslint/img_src_cdn.js
  packages/eslint/index.js
  packages/eslint/variable_name_check.js
Labels: 1 min review

#27 Zeroth-index-fix
  packages/eslint/zeroth_index_import.js
Labels: 1 min review

#5 Img src cdn
  .github/CODEOWNERS
  .gitignore
  custom-eslint-rules.js
  custom-rules.js
  package.json
  packages/custom-eslint/index.js
  packages/custom-eslint/package.json
  packages/custom-eslint/rules/check_element_role_button.js
  packages/custom-eslint/rules/cl_for_merging_styles_class.js
  packages/custom-eslint/rules/component_pascal.js
  packages/custom-eslint/rules/date_time_format_check.js
  packages/custom-eslint/rules/default_comp_props.js
  packages/custom-eslint/rules/default_usestate.js
  packages/custom-eslint/rules/email_check.js
  packages/custom-eslint/rules/hook_sequence.js
  packages/custom-eslint/rules/img_src_cdn.js
  packages/custom-eslint/rules/is_empty_use_check.js
  packages/custom-eslint/rules/key_as_function.js
  packages/custom-eslint/rules/key_in_for_each_map.js
  packages/custom-eslint/rules/nbsp_ensp_check.js
  packages/custom-eslint/rules/regex_check.js
  packages/custom-eslint/rules/uuid_check.js
  packages/custom-eslint/rules/variable_name_check.js
  packages/custom-eslint/rules/variable_value_jsx.js
  packages/custom-eslint/rules/variables_name_check.js
  packages/custom-eslint/rules/zeroth_index_import.js
  packages/custom-stylelint/package.json
  packages/eslint/index.js
Labels: 30 min review
